language: rust
cache: cargo
rust:
        - 1.26.0 # oldest supported version
        - stable
        - beta
        - nightly
matrix:
        allow_failures:
                - rust: nightly
        fast_finish: true
