[package]
name = "exitfailure"
version = "0.4.0"
authors = ["Toby Smith <toby@tismith.id.au>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/tismith/exitfailure"
description = "A basic newtype wrapper around failure::Error"
categories = ["command-line-interface"]
keywords = ["newtype", "failure", "error", "command-line", "cli"]

[dependencies]
failure = "0.1.1"

[dev-dependencies]
assert_cli = "0.6"

[badges]
travis-ci = { repository = "tismith/exitfailure", branch = "master" }
codecov = { repository = "tismith/exitfailure", branch = "master", service = "github" }
