[package]
name = "exitfailure"
version = "0.3.0"
authors = ["Toby Smith <toby@tismith.id.au>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/tismith/exitfailure"
description = "A basic newtype wrapper around failure::Error"

[dependencies]
failure = "0.1.1"

[dev-dependencies]
assert_cli = "0.5"

[badges]
travis-ci = { repository = "tismith/exitfailure", branch = "master" }
